modules:
  - name: "Coding Study"
    lessons:
      - name: "About the Study"
        file: "study/01-about.md"
        shortName: "about"
      - name: "Consent"
        file: "study/02-consent.md"
        shortName: "consent"
      - name: "Pre-Survey"
        file: "study/03-pre-survey.md"
        shortName: "pre-survey"
      - name: "Lesson Instructions"
        file: "study/04-instructions.md"
        shortName: "instructions"
      - name: "Lesson 1: Operators"
        file: "study/05-lesson-operators.md"
        shortName: "lesson-1"
      - name: "Lesson 2: Variables"
        file: "study/06-lesson-variables.md"
        shortName: "lesson-2"
      - name: "Lesson 3: Vectors and Functions"
        file: "study/07-lesson-vectors-and-functions.md"
        shortName: "lesson-3"
      - name: "Lesson 4: Data Frames and More Functions"
        file: "study/08-lesson-data-frames.md"
        shortName: "lesson-4"
      - name: "Lesson Summary"
        file: "study/09-lesson-summary.md"
        shortName: "lesson-summary"
    
